### PR TITLE
draft: improved configuration file

### PR DESCRIPTION
**Pull request by calops**
There you go, here's the result of my personal brainstorming about how a lua config file could look, both in its complex details and its more user-friendly sugar.

The idea is to provide a powerful underlying system, and then a bunch of well documented helper functions on top of this to cover 99% of use-cases, so that a normal config file looks clean and easy to understand by anybody, even if they don't know anything about lua.

Prominently, I did away with the global variables (they're arbitrary and throw off language servers as they're not in scope by default) and instead put everything into the `strata` module as setter functions. The bonus is that they can also act as an API that plugins (or users) can use to dynamically set things.

Let me know what you think, and if you see how we could make this even more user-friendly.

### CODE REVIEW

**Comment by vazw** [comment]
Great! ,This way we can directly store `cmd` for keybinds to  `Box` Directly.

```rust
struct Keybinding {
    keys: Vec<String>,
    cmd: Box<dyn Fn()>,
}
```

```rust
let keys: Vec<String> = binding_table.get("keys")?;
let cmd_func: Function = binding_table.get("cmd")?;
            
let cmd = Box::new(move || {
cmd_func.call::<_, ()>(()).unwrap();
});
            
bindings.push(Keybinding { keys, cmd });
```
What do you think?

**Comment by calops** [comment]
That's a good way to set default keybindings within the WM itself, yes. Although ideally you won't need to `get()` entries in a table since everything should be deserialized cleanly in a struct.

However, as I wrote in the comments, I see value in having, at the lowest level, only one powerful abstraction to cover all use-cases.

The `rules` framework could (and should, if we go this way) be leveraged to implement key bindings as well. You'd have an events listener that produces its own key events, that are then dispatched as triggers to the rules that subscribe to these events.

On the lua side, you'd have these two equivalent things, one being sugar on top of the other:

```lua
strata.set_bindings {
	{
		keys = { "CTRL", "R" },
		action = strata.restart_wm,
	}
}

strata.set_rules {
	{
		triggers = { { keys = { "CTRL", "R" } },
		action = strata.restart_wm,
	}
}
```

With the equivalent rust structs and functions underneath it all. Although it makes me wonder if it wouldn't be worth it to simply scrap `set_bindings` and have something like this:

```lua
strata.set_rules {
	strata.rules.binding({ "CTRL", "R" }, strata.restart_wm),

	-- Or maybe something like this
	strata.rules.bindings {
		{
			keys = { "CTRL", "R" },
			action = strata.restart_wm,
		},

		-- Possibly have them as a list rather than a dict (or maybe allow both)
		{ {"CTRL", "R"}, strata.restart_wm },

		-- Maybe we could even parse vim keys notation for ease of writing
		{ "C-r", strata.restart_wm },
	}
}
```

**Review by anantnrg — APPROVED** [review]
This is actually pretty great! I never expected Lua to be this beautiful.

**Comment by calops** [comment]
I will probably iterate a bit more on this (I'm not fond of the naming of the functions I've written here, for example), but I'm glad you like it!

**Comment by vazw** [comment]
I try to play around `set_bindings` function and past `spawn` as LuaFuntion to `strata.cmd` 

image
image

But `strata.cmd.spawn()` does not stored as `FunctionWarpper` but it got excuted at the `.exec()` right away.

image

any idea?.

**Comment by anantnrg** [comment]
Hey @vazw, I'm working on that now. I've updated the code quite a bit in the `lua_rust` repo, if you could replicate these changes there, it would be great. Also, please make any future comments on the original issue [here](https://github.com/stratawm/stratawm/issues/3) so that it's a bit easier to keep track of the changes.

Also since we're already here, I'd like to know what font you're using. It looks pretty great!

**Comment by vazw** [comment]
Alright, I need to playaround for a while I found my self lacking some knowledge and need some time to keep up on this.

> Also since we're already here, I'd like to know what font you're using. It looks pretty great!

It's `FiraCode Nerd Font`

**Comment by anantnrg** [comment]
Okay, thx!

**Pull request merged**
