### PR TITLE
Draft: luaconf experiment

### PR DESCRIPTION
**Pull request by calops**
I'm putting this here but it's not finished. What I'm trying to do:

* Move some stuff from rust to lua. It's much shorter to write, has less overhead, and should be easier to maintain that way. The idea is to have rust callbacks only for code that is either impossible, significantly harder to write, or less performant in lua. I still need to add these lua modules to the runtime path, but they already work when loading the file from the project's root.
* Use an `RwLock` (from `parking_lot`) instead of a `Mutex` to access the configuration.
* Split the configuration in three parts that are independent, to avoid locking everything every time.
* Use actual `Function`s as callbacks for actions. This is what's causing the compilation to fail right now, as I'm having trouble with `mlua` and `parking_lot` not playing nice together (even though they should).
* Flesh out the configuration options and try to make deserialization work (it doesn't yet) for everything seamlessly. In particular, for ergonomic reasons rules should work when nested, which will probably require a bit of manual deserialization.

The PR is not ready but it's where I'm at today. I will try to finis this tomorrow, but in the meantime I'll be glad to hear feedback.

### CODE REVIEW

**Comment by vazw** [comment]
wow adding 'RWlock'  is much more easier to read and understand. 

there's no progress on my side here I gotta finish my sprint in a few days.

I'll keep up on ya later. Great work⚡⚡

**Review by anantnrg — APPROVED** [review]
This looks pretty good. Much cleaner than doing everything in Rust

**Review by anantnrg — APPROVED** [review]
I think we can merge these changes. Looks great!

**Comment by calops** [comment]
I'm glad you like it, but I haven't tested it yet so it probably doesn't work, at least the deser part. I'll work on it today.

**Comment by anantnrg** [comment]
Yeah, it currently doesn't work. Some part of the `options` table isn't being parsed properly because the returned workspaces count is 0. I can't work on it this week cause my exams start tomorrow but if you have some updates, you can create a PR. I'll check it out and merge it. Cheers :)

**Comment by calops** [comment]
Hm, weird. I'll look into it.

**Comment by vazw** [comment]
`parse_config()` seem to not work. is there any progress? I can help by the weekend.
// I'm using NixOS now

image

**Comment by anantnrg** [comment]
Yep, that's the problem rn. No updates from my side. I can't look at it today, or for the next week for that matter cause my exams started today. But I'll gladly checkout and merge a PR if you create one. Cheers :)

**Comment by calops** [comment]
Hey, I found the issue: we need to add the `lua` folder to the global scope of mlua so that it's accessible from an actual user's config file.

Shouldn't be too hard to do, just need to find out how to add paths to the scope in mlua. I'll try to push something today.

**Pull request merged**
