### PR TITLE
tentative fix for configuration

### PR DESCRIPTION
**Pull request by calops**
I haven't had time to test this, but the gist is: add the `./lua` files to the global lua modules path so that they're found when loading the config file.

Right now the install dir is hardcoded, which is obviously something we should change.

Oh and also some code cleanup here and there.

### CODE REVIEW

**Comment by anantnrg** [comment]
I don't have much time to go through this thoroughly 'cause i have an exam in an hour, but from what I've seen, it looks pretty good. I'll merge this for now. I'll check it out in the evening or maybe on Sunday. Cheers :)

**Comment by anantnrg** [comment]
Hey @calops, I got a chance to look at it now and it still seems that the `set_config` function isn't called. I'm going through the code right now. Do you have any updates?

**Comment by anantnrg** [comment]
On further inspection, none of the Lua helper files are being called.

**Comment by calops** [comment]
Where is your stratawm installed when you test it?

We need to properly detect where the program is installed so we can provide the correct path to lua so that the modules are in scope. Right now I hardcoded the default one in `/usr/lib/stratawm/lua`. Although I'm not sure if even this works but I'm gonna have time tonight to look into it.

Out of curiosity, does it work if you replace `strata.set_config` with `require("strata.api").set_config`?

**Comment by calops** [comment]
Oh I noticed a typo as well, I'll send a PR to fix it.

**Comment by anantnrg** [comment]
Hey @calops, I've changed the Makefile quite a lot so now im testing if the libs are being copied to the right paths. I'll create a PR with the changes now.

**Pull request merged**
